modLoader = "lowcodefml"
loaderVersion = "${forge_loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/ryanhcode/sable/issues"

[[mods]]
modId = "sablecompanion"
version = "${version}"
displayName = "Sable Companion"
logoFile = "sablecompanion.png"
authors = "RyanHCode"
description = '''Lightweight API for mods that want to interact with Sable sub-levels without depending on Sable.'''

[[dependencies.sablecompanion]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
